const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const elements={};let stored=null,storedRevision=0,fail=false;
const db={auth:{onAuthStateChange(){},getSession:async()=>({data:{session:null}})},from(){return{select(){return{eq(){return{maybeSingle:async()=>({data:stored?{document:structuredClone(stored),revision:storedRevision}:null})}}}}}},rpc:async(_name,args)=>{if(fail)return{error:{message:'Network failure'}};if(args.p_revision!==storedRevision)return{error:{message:'REVISION_CONFLICT',code:'40001'}};stored=structuredClone(args.p_document);return{data:++storedRevision}}};
const context=vm.createContext({console,Intl,Date,structuredClone,crypto:require('node:crypto').webcrypto,setTimeout:()=>{},Option:function(t,v){this.value=v},confirm:()=>true,location:{origin:'https://example.test',pathname:'/'},document:{body:{classList:{toggle(){}}},querySelector:s=>elements[s]??={value:s==='#year'?'2026':'',checked:false,innerHTML:'',textContent:'',style:{},classList:{add(){},remove(){}},options:[{value:'2026'},{value:'2027'}],add(o){this.options.push(o)},showModal(){this.open=true},close(){this.open=false},reset(){},reportValidity(){return true}},querySelectorAll:()=>[]},window:{supabase:{createClient:()=>db},addEventListener(){}}});
for(const file of ['app.js','persistence.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);
(async()=>{
 await new Promise(r=>setImmediate(r));
 await vm.runInContext("acceptSession({user:{id:'owner',email:'owner@example.test'}})",context);
 await vm.runInContext(`(async()=>{ $('#year').value='2026';openEdit(14,10,2026);$('#manual').value='100';$('#purchaseTitle').value='Teste';$('#purchaseValue').value='600';$('#parts').value='6';$('#buy').onclick();await $('#editform').onsubmit({preventDefault(){}})})()`,context);
 assert.equal(storedRevision,1);assert.equal(stored.records['14-2027-3'].purchases[0].part,6);assert.equal(stored.records['14-2026-10'].manual,100);
 const initial=structuredClone(stored);
 fail=true;
 await vm.runInContext(`(async()=>{openEdit(14,10,2026);$('#manual').value='999';await $('#editform').onsubmit({preventDefault(){}})})()`,context);
 assert.deepEqual(stored,initial);assert.equal(vm.runInContext("records['14-2026-10'].manual",context),100);assert.match(elements['#sync-status'].textContent,/Não foi possível salvar/);
 fail=false;
 await vm.runInContext('loadBudget(currentUser)',context);
 assert.equal(vm.runInContext("records['14-2027-3'].purchases[0].part",context),6);
 await vm.runInContext("(async()=>{openEdit(14,11,2026);await $('#delete-current').onclick()})()",context);
 assert.equal(stored.records['14-2026-11'],undefined);assert.ok(stored.records['14-2027-0']);
 await vm.runInContext("(async()=>{openEdit(14,0,2027);await $('#delete-future').onclick()})()",context);
 assert.ok(stored.records['14-2026-10']);assert.equal(stored.records['14-2027-3'],undefined);
 await vm.runInContext(`(async()=>{openEdit(14,10,2026);$('#status').value='paid';$('#actual').value='100';$('#paiddate').value='2026-11-10';await $('#editform').onsubmit({preventDefault(){}});selectedMonth=10;await $('#archive-month').onclick()})()`,context);
 assert.ok(stored.archived.includes(2026*12+10));
 await vm.runInContext(`(async()=>{openEdit(14,10,2026);$('#purchaseTitle').value='Nova';$('#purchaseValue').value='10';$('#parts').value='1';$('#buy').onclick();await $('#editform').onsubmit({preventDefault(){}})})()`,context);
 assert.ok(!stored.archived.includes(2026*12+10));
 storedRevision++;
 await vm.runInContext(`(async()=>{openEdit(14,10,2026);$('#manual').value='555';await $('#editform').onsubmit({preventDefault(){}})})()`,context);
 assert.notEqual(stored.records['14-2026-10'].manual,555);assert.match(elements['#sync-status'].textContent,/Outra janela/);
 await vm.runInContext('loadBudget(currentUser)',context);
 const recordsBeforeFormula=structuredClone(stored.records);
 for(const [input,expected] of [['=1500+250,50+100',1850.5],['=0,10+0,20',0.3],['1.500,25',1500.25],['1500.25',1500.25],['=1.000+2.000',3000],['=0+0',0]])assert.equal(vm.runInContext(`parseExpectedValue(${JSON.stringify(input)}).value`,context),expected);
 for(const input of ['=',' =1+','1+2','=alert(1)','=10/0','=1,234','=1++2','-10','=1e3'])assert.throws(()=>vm.runInContext(`parseExpectedValue(${JSON.stringify(input)})`,context));
 await vm.runInContext("(async()=>{openEdit(1,0,2026);$('#value').value='=1500+250,50+100';await $('#editform').onsubmit({preventDefault(){}});await loadBudget(currentUser);openEdit(1,0,2026)})()",context);
 assert.equal(stored.records['1-2026-0'].value,1850.5);assert.equal(elements['#value'].value,'=1500+250,50+100');
 await vm.runInContext("(async()=>{$('#value').value='=1+';await $('#editform').onsubmit({preventDefault(){}})})()",context);assert.equal(stored.records['1-2026-0'].value,1850.5);
 await vm.runInContext("(async()=>{$('#value').value='2000,50';await $('#editform').onsubmit({preventDefault(){}})})()",context);assert.equal(stored.records['1-2026-0'].valueFormula,null);assert.equal(stored.records['1-2026-0'].value,2000.5);
 for(const [k,v]of Object.entries(recordsBeforeFormula))assert.deepEqual(stored.records[k],v);
 const recordsBeforeRename=structuredClone(stored.records);
 await vm.runInContext("(async()=>{openRowEdit(14);$('#row-name').value='Nubank pessoal';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.rows.find(r=>r.id===14).name,'Nubank pessoal');assert.deepEqual(stored.records,recordsBeforeRename);
 await vm.runInContext("(async()=>{openRowEdit(6);$('#row-name').value='Internet casa';$('#row-group').value='4';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.rows.find(r=>r.id===6).group,4);assert.deepEqual(stored.records,recordsBeforeRename);
 fail=true;
 await vm.runInContext("(async()=>{openRowEdit(14);$('#row-name').value='Nome não salvo';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(vm.runInContext("rows.find(r=>r.id===14).name",context),'Nubank pessoal');assert.equal(elements['#row-editor'].open,true);
 fail=false;
 await vm.runInContext("(async()=>{openRowEdit(14);$('#row-name').value='Nome';$('#row-group').value='1';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.rows.find(r=>r.id===14).group,7);
 await vm.runInContext("(async()=>{$('#newname').value='Internet fixa';$('#group').value='1';await $('#newform').onsubmit({preventDefault(){}})})()",context);
 const fixedId=stored.rows.find(r=>r.name==='Internet fixa').id;
 context.fixedId=fixedId;
 assert.equal(stored.rows.find(r=>r.id===fixedId).recurrences,undefined);
 await vm.runInContext("(async()=>{openEdit(fixedId,0,2026);$('#value').value='=80+20';$('#due').value='2026-01-31';$('#repeat-monthly').checked=true;await $('#editform').onsubmit({preventDefault(){}})})()",context);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),1,2026).due",context),'2026-02-28');
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),1,2028).due",context),'2028-02-29');
 await vm.runInContext("(async()=>{openEdit(fixedId,0,2026);$('#entry-description').value='Somente janeiro';$('#status').value='paid';$('#actual').value='100';$('#paiddate').value='2026-01-31';await $('#editform').onsubmit({preventDefault(){}});openEdit(fixedId,1,2026);$('#value').value='125';await $('#editform').onsubmit({preventDefault(){}});openEdit(fixedId,2,2026);$('#entry-description').value='Plano mensal atualizado';$('#value').value='200';$('#repeat-scope').value='future';await $('#editform').onsubmit({preventDefault(){}})})()",context);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),0,2026).paid",context),true);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),1,2026).value",context),125);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),3,2026).value",context),200);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),0,2026).description",context),'Somente janeiro');
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),1,2026).description",context),'');
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),3,2026).description",context),'Plano mensal atualizado');

 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),3,2026).due",context),'2026-04-30');
 await vm.runInContext("(async()=>{openEdit(fixedId,3,2026);await $('#delete-current').onclick();await loadBudget(currentUser)})()",context);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),3,2026).value",context),null);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),4,2026).value",context),200);
 await vm.runInContext("(async()=>{openEdit(fixedId,5,2026);await $('#delete-future').onclick();await loadBudget(currentUser)})()",context);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),4,2026).value",context),200);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),5,2026).value",context),null);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),1,2030).value",context),null);
 fail=true;
 await vm.runInContext("(async()=>{openEdit(fixedId,6,2026);$('#value').value='300';$('#due').value='2026-07-10';$('#repeat-monthly').checked=true;await $('#editform').onsubmit({preventDefault(){}})})()",context);
 assert.equal(vm.runInContext("rec(rows.find(r=>r.id===fixedId),7,2026).value",context),null);fail=false;
 await vm.runInContext("(async()=>{openEdit(1,0,2026);$('#entry-description').value='<b>Salário</b>\\nInclui adicional';await $('#editform').onsubmit({preventDefault(){}});await loadBudget(currentUser);openEdit(1,0,2026)})()",context);
 assert.equal(elements['#entry-description'].value,'<b>Salário</b>\nInclui adicional');
 assert.equal(stored.records['1-2026-0'].value,2000.5);
 const descriptionBefore=stored.records['1-2026-0'].description;
 await vm.runInContext("(async()=>{$('#entry-description').value='x'.repeat(2001);await $('#editform').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.records['1-2026-0'].description,descriptionBefore);
 fail=true;
 await vm.runInContext("(async()=>{$('#entry-description').value='Não salvo';await $('#editform').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.records['1-2026-0'].description,descriptionBefore);fail=false;
 await vm.runInContext("(async()=>{openEdit(1,0,2026);$('#entry-description').value='';await $('#editform').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.records['1-2026-0'].description,'');
 const recordsBeforeGeneral=structuredClone(stored.records);
 await vm.runInContext("(async()=>{openRowEdit(6);$('#row-description').value='<b>Endereço</b>\\nInscrição 123';await $('#row-edit-form').onsubmit({preventDefault(){}});await loadBudget(currentUser);openRowEdit(6)})()",context);
 assert.equal(elements['#row-description'].value,'<b>Endereço</b>\nInscrição 123');
 assert.deepEqual(stored.records,recordsBeforeGeneral);
 vm.runInContext('openEdit(6,0,2026)',context);
 assert.equal(elements['#account-description-text'].textContent,'<b>Endereço</b>\nInscrição 123');assert.equal(elements['#account-description-panel'].hidden,false);
 fail=true;
 await vm.runInContext("(async()=>{openRowEdit(6);$('#row-description').value='Não salvo';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.rows.find(r=>r.id===6).description,'<b>Endereço</b>\nInscrição 123');fail=false;
 await vm.runInContext("(async()=>{openRowEdit(6);$('#row-description').value='';await $('#row-edit-form').onsubmit({preventDefault(){}});openEdit(6,0,2026)})()",context);
 assert.equal(elements['#account-description-panel'].hidden,true);
 const beforeCategoryChange=structuredClone(stored.records);
 await vm.runInContext("(async()=>{openRowEdit(1);if($('#row-group').disabled)throw Error('Income category is locked');$('#row-group').value='1';await $('#row-edit-form').onsubmit({preventDefault(){}});await loadBudget(currentUser)})()",context);
 assert.equal(stored.rows.find(r=>r.id===1).group,1);assert.deepEqual(stored.records,beforeCategoryChange);
 await vm.runInContext("(async()=>{openRowEdit(1);$('#row-group').value='0';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.rows.find(r=>r.id===1).group,0);assert.deepEqual(stored.records,beforeCategoryChange);
 const beforeHide=structuredClone(stored.records);
 const metricsBeforeHide=elements['#metrics'].innerHTML;
 await vm.runInContext("(async()=>{openRowEdit(6);$('#row-hidden').checked=true;await $('#row-edit-form').onsubmit({preventDefault(){}});await loadBudget(currentUser)})()",context);
 assert.equal(stored.rows.find(r=>r.id===6).hidden,true);
 assert.deepEqual(stored.records,beforeHide);assert.equal(elements['#metrics'].innerHTML,metricsBeforeHide);
 assert.ok(!elements['#budget'].innerHTML.includes('data-edit-row="6"'));
 vm.runInContext("$('#show-hidden').checked=true;$('#show-hidden').onchange()",context);
 assert.ok(elements['#budget'].innerHTML.includes('data-edit-row="6"'));assert.ok(elements['#budget'].innerHTML.includes('>Oculta</small>'));
 fail=true;
 await vm.runInContext("(async()=>{openRowEdit(6);$('#row-hidden').checked=false;await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(vm.runInContext('rows.find(r=>r.id===6).hidden',context),true);fail=false;
 await vm.runInContext("(async()=>{openRowEdit(6);$('#row-hidden').checked=false;await $('#row-edit-form').onsubmit({preventDefault(){}});$('#show-hidden').checked=false;render()})()",context);
 assert.equal(stored.rows.find(r=>r.id===6).hidden,false);assert.ok(elements['#budget'].innerHTML.includes('data-edit-row="6"'));
 await vm.runInContext("(async()=>{await $('#sort-accounts').onclick();await loadBudget(currentUser)})()",context);
 const ordered=stored.rows.map(r=>r.id);
 assert.deepEqual(ordered,[...stored.rows].sort((a,b)=>a.group-b.group||a.name.localeCompare(b.name,'pt-BR',{sensitivity:'base',numeric:true})).map(r=>r.id));
 assert.deepEqual(stored.records,beforeHide);assert.equal(elements['#metrics'].innerHTML,metricsBeforeHide);
 // Whole-card deletion requires confirmation and preserves other accounts.
 await vm.runInContext("(async()=>{openEdit(14,2,2028);$('#manual').value='50';await $('#editform').onsubmit({preventDefault(){}});openEdit(14,2,2028);$('#delete-row').onclick()})()",context);
 assert.equal(elements['#delete-dialog'].open,true);
 assert.equal(elements['#delete-all'].textContent,'Excluir cartão e todo o histórico');
 const beforeDeleteAll=structuredClone(stored);
 context.confirm=()=>false;
 await vm.runInContext("$('#delete-all').onclick()",context);
 assert.deepEqual(stored,beforeDeleteAll);
 context.confirm=()=>true;fail=true;
 await vm.runInContext("$('#delete-all').onclick()",context);
 assert.deepEqual(stored,beforeDeleteAll);
 assert.equal(vm.runInContext('rows.some(r=>r.id===14)',context),true);
 assert.equal(elements['#editor'].open,true);
 fail=false;
 await vm.runInContext("(async()=>{$('#delete-row').onclick();await $('#delete-all').onclick();await loadBudget(currentUser)})()",context);
 assert.equal(stored.rows.some(r=>r.id===14),false);
 assert.equal(Object.keys(stored.records).some(k=>k.startsWith('14-')),false);
 assert.deepEqual(stored.rows,beforeDeleteAll.rows.filter(r=>r.id!==14));
 assert.deepEqual(stored.records,Object.fromEntries(Object.entries(beforeDeleteAll.records).filter(([k])=>!k.startsWith('14-'))));
 assert.ok(!elements['#budget'].innerHTML.includes('data-edit-row="14"'));
 // A failed scoped deletion can also be retried from the restored editor.
 fail=true;
 await vm.runInContext("(async()=>{openEdit(1,0,2026);await $('#delete-current').onclick()})()",context);
 assert.ok(stored.records['1-2026-0']);fail=false;
 await vm.runInContext("(async()=>{$('#delete-row').onclick();await $('#delete-current').onclick()})()",context);
 assert.equal(stored.records['1-2026-0'],undefined);
 await vm.runInContext('acceptSession(null)',context);assert.equal(vm.runInContext('Object.keys(records).length',context),0);
 console.log('PASS: durable roundtrip, payment, archive/reopen, cross-year installments, scoped deletion, failure rollback, conflict handling and logout isolation.');
})().catch(e=>{console.error(e);process.exitCode=1});
