const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const elements={};let stored=null,storedRevision=0,fail=false;
const db={auth:{onAuthStateChange(){},getSession:async()=>({data:{session:null}})},from(){return{select(){return{eq(){return{maybeSingle:async()=>({data:stored?{document:structuredClone(stored),revision:storedRevision}:null})}}}}}},rpc:async(_name,args)=>{if(fail)return{error:{message:'Network failure'}};if(args.p_revision!==storedRevision)return{error:{message:'REVISION_CONFLICT',code:'40001'}};stored=structuredClone(args.p_document);return{data:++storedRevision}}};
const context=vm.createContext({console,Intl,Date,structuredClone,crypto:require('node:crypto').webcrypto,setTimeout:()=>{},Option:function(t,v){this.value=v},confirm:()=>true,location:{origin:'https://example.test',pathname:'/'},document:{body:{classList:{toggle(){}}},querySelector:s=>elements[s]??={value:s==='#year'?'2026':'',checked:false,innerHTML:'',textContent:'',style:{},options:[{value:'2026'},{value:'2027'}],add(o){this.options.push(o)},showModal(){this.open=true},close(){this.open=false},reset(){},reportValidity(){return true}},querySelectorAll:()=>[]},window:{supabase:{createClient:()=>db},addEventListener(){}}});
for(const file of ['app.js','persistence.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);
(async()=>{
 await new Promise(r=>setImmediate(r));
 await vm.runInContext("acceptSession({user:{id:'owner',email:'owner@example.test'}})",context);
 await vm.runInContext(`(async()=>{ $('#year').value='2026';openEdit(14,10,2026);$('#manual').value='100';$('#purchaseTitle').value='Teste';$('#purchaseValue').value='600';$('#parts').value='6';$('#buy').onclick();await $('#editform').onsubmit({preventDefault(){}})})()`,context);
 assert.equal(storedRevision,1);assert.equal(stored.records['14-2027-3'].purchases[0].part,6);assert.equal(stored.records['14-2026-10'].manual,100);
 const initial=structuredClone(stored);
 fail=true;
 await vm.runInContext(`(async()=>{openEdit(14,10,2026);$('#manual').value='999';await $('#editform').onsubmit({preventDefault(){}})})()`,context);
 assert.deepEqual(stored,initial);assert.equal(vm.runInContext("records['14-2026-10'].manual",context),100);assert.match(elements['#sync-status'].textContent,/Não foi possível salvar/);
 fail=false;
 await vm.runInContext('loadBudget(currentUser)',context);
 assert.equal(vm.runInContext("records['14-2027-3'].purchases[0].part",context),6);
 await vm.runInContext("(async()=>{openEdit(14,11,2026);await $('#delete-current').onclick()})()",context);
 assert.equal(stored.records['14-2026-11'],undefined);assert.ok(stored.records['14-2027-0']);
 await vm.runInContext("(async()=>{openEdit(14,0,2027);await $('#delete-future').onclick()})()",context);
 assert.ok(stored.records['14-2026-10']);assert.equal(stored.records['14-2027-3'],undefined);
 await vm.runInContext(`(async()=>{openEdit(14,10,2026);$('#status').value='paid';$('#actual').value='100';$('#paiddate').value='2026-11-10';await $('#editform').onsubmit({preventDefault(){}});selectedMonth=10;await $('#archive-month').onclick()})()`,context);
 assert.ok(stored.archived.includes(2026*12+10));
 await vm.runInContext(`(async()=>{openEdit(14,10,2026);$('#purchaseTitle').value='Nova';$('#purchaseValue').value='10';$('#parts').value='1';$('#buy').onclick();await $('#editform').onsubmit({preventDefault(){}})})()`,context);
 assert.ok(!stored.archived.includes(2026*12+10));
 storedRevision++;
 await vm.runInContext(`(async()=>{openEdit(14,10,2026);$('#manual').value='555';await $('#editform').onsubmit({preventDefault(){}})})()`,context);
 assert.notEqual(stored.records['14-2026-10'].manual,555);assert.match(elements['#sync-status'].textContent,/Outra janela/);
 await vm.runInContext('loadBudget(currentUser)',context);
 const recordsBeforeRename=structuredClone(stored.records);
 await vm.runInContext("(async()=>{openRowEdit(14);$('#row-name').value='Nubank pessoal';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.rows.find(r=>r.id===14).name,'Nubank pessoal');assert.deepEqual(stored.records,recordsBeforeRename);
 await vm.runInContext("(async()=>{openRowEdit(6);$('#row-name').value='Internet casa';$('#row-group').value='4';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.rows.find(r=>r.id===6).group,4);assert.deepEqual(stored.records,recordsBeforeRename);
 fail=true;
 await vm.runInContext("(async()=>{openRowEdit(14);$('#row-name').value='Nome não salvo';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(vm.runInContext("rows.find(r=>r.id===14).name",context),'Nubank pessoal');assert.equal(elements['#row-editor'].open,true);
 fail=false;
 await vm.runInContext("(async()=>{openRowEdit(14);$('#row-name').value='Nome';$('#row-group').value='1';await $('#row-edit-form').onsubmit({preventDefault(){}})})()",context);
 assert.equal(stored.rows.find(r=>r.id===14).group,7);
 await vm.runInContext('acceptSession(null)',context);assert.equal(vm.runInContext('Object.keys(records).length',context),0);
 console.log('PASS: durable roundtrip, payment, archive/reopen, cross-year installments, scoped deletion, failure rollback, conflict handling and logout isolation.');
})().catch(e=>{console.error(e);process.exitCode=1});
